/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Article service. Represents a row in the &quot;AmfNewsletter_Article&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.newsletter.model.impl.ArticleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.newsletter.model.impl.ArticleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Article
 * @generated
 */
@ProviderType
public interface ArticleModel extends BaseModel<Article>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a article model instance should use the {@link Article} interface instead.
	 */

	/**
	 * Returns the primary key of this article.
	 *
	 * @return the primary key of this article
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this article.
	 *
	 * @param primaryKey the primary key of this article
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the article ID of this article.
	 *
	 * @return the article ID of this article
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this article.
	 *
	 * @param articleId the article ID of this article
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the issue number of this article.
	 *
	 * @return the issue number of this article
	 */
	public long getIssueNumber();

	/**
	 * Sets the issue number of this article.
	 *
	 * @param issueNumber the issue number of this article
	 */
	public void setIssueNumber(long issueNumber);

	/**
	 * Returns the order of this article.
	 *
	 * @return the order of this article
	 */
	public long getOrder();

	/**
	 * Sets the order of this article.
	 *
	 * @param order the order of this article
	 */
	public void setOrder(long order);

	/**
	 * Returns the company ID of this article.
	 *
	 * @return the company ID of this article
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this article.
	 *
	 * @param companyId the company ID of this article
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the title of this article.
	 *
	 * @return the title of this article
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this article.
	 *
	 * @param title the title of this article
	 */
	public void setTitle(String title);

	/**
	 * Returns the author of this article.
	 *
	 * @return the author of this article
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this article.
	 *
	 * @param author the author of this article
	 */
	public void setAuthor(String author);

	/**
	 * Returns the content of this article.
	 *
	 * @return the content of this article
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this article.
	 *
	 * @param content the content of this article
	 */
	public void setContent(String content);

	/**
	 * Returns the create date of this article.
	 *
	 * @return the create date of this article
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this article.
	 *
	 * @param createDate the create date of this article
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this article.
	 *
	 * @return the modified date of this article
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this article.
	 *
	 * @param modifiedDate the modified date of this article
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the journal article ID of this article.
	 *
	 * @return the journal article ID of this article
	 */
	@AutoEscape
	public String getJournalArticleId();

	/**
	 * Sets the journal article ID of this article.
	 *
	 * @param journalArticleId the journal article ID of this article
	 */
	public void setJournalArticleId(String journalArticleId);

	@Override
	public Article cloneWithOriginalValues();

}