/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserExternal service. Represents a row in the &quot;AmfRegistration_UserExternal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.registration.model.impl.UserExternalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.registration.model.impl.UserExternalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserExternal
 * @generated
 */
@ProviderType
public interface UserExternalModel
	extends BaseModel<UserExternal>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user external model instance should use the {@link UserExternal} interface instead.
	 */

	/**
	 * Returns the primary key of this user external.
	 *
	 * @return the primary key of this user external
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user external.
	 *
	 * @param primaryKey the primary key of this user external
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user external ID of this user external.
	 *
	 * @return the user external ID of this user external
	 */
	public long getUserExternalId();

	/**
	 * Sets the user external ID of this user external.
	 *
	 * @param userExternalId the user external ID of this user external
	 */
	public void setUserExternalId(long userExternalId);

	/**
	 * Returns the company ID of this user external.
	 *
	 * @return the company ID of this user external
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user external.
	 *
	 * @param companyId the company ID of this user external
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user external.
	 *
	 * @return the user ID of this user external
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user external.
	 *
	 * @param userId the user ID of this user external
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user external.
	 *
	 * @return the user uuid of this user external
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user external.
	 *
	 * @param userUuid the user uuid of this user external
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the male of this user external.
	 *
	 * @return the male of this user external
	 */
	public int getMale();

	/**
	 * Sets the male of this user external.
	 *
	 * @param male the male of this user external
	 */
	public void setMale(int male);

	/**
	 * Returns the create date of this user external.
	 *
	 * @return the create date of this user external
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user external.
	 *
	 * @param createDate the create date of this user external
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user external.
	 *
	 * @return the modified date of this user external
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user external.
	 *
	 * @param modifiedDate the modified date of this user external
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public UserExternal cloneWithOriginalValues();

}