/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.user.profile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FavoriteGenre service. Represents a row in the &quot;AmfUserProfile_FavoriteGenre&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.user.profile.model.impl.FavoriteGenreModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.user.profile.model.impl.FavoriteGenreImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FavoriteGenre
 * @generated
 */
@ProviderType
public interface FavoriteGenreModel extends BaseModel<FavoriteGenre> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a favorite genre model instance should use the {@link FavoriteGenre} interface instead.
	 */

	/**
	 * Returns the primary key of this favorite genre.
	 *
	 * @return the primary key of this favorite genre
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this favorite genre.
	 *
	 * @param primaryKey the primary key of this favorite genre
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the favorite genre ID of this favorite genre.
	 *
	 * @return the favorite genre ID of this favorite genre
	 */
	public long getFavoriteGenreId();

	/**
	 * Sets the favorite genre ID of this favorite genre.
	 *
	 * @param favoriteGenreId the favorite genre ID of this favorite genre
	 */
	public void setFavoriteGenreId(long favoriteGenreId);

	/**
	 * Returns the favorite genre name of this favorite genre.
	 *
	 * @return the favorite genre name of this favorite genre
	 */
	@AutoEscape
	public String getFavoriteGenreName();

	/**
	 * Sets the favorite genre name of this favorite genre.
	 *
	 * @param favoriteGenreName the favorite genre name of this favorite genre
	 */
	public void setFavoriteGenreName(String favoriteGenreName);

	@Override
	public FavoriteGenre cloneWithOriginalValues();

}